# Database credentials. The password is generated by Terraform and stored only in
# Secrets Manager; the Lambdas read it at runtime via DB_SECRET_ARN.
resource "aws_secretsmanager_secret" "db" {
  name        = "${local.name_prefix}/db-credentials"
  description = "Postgres credentials for the lead assignment engine."
  tags        = local.common_tags
}

resource "aws_secretsmanager_secret_version" "db" {
  secret_id = aws_secretsmanager_secret.db.id
  secret_string = jsonencode({
    username = var.db_username
    password = random_password.db.result
    host     = aws_db_instance.postgres.address
    port     = aws_db_instance.postgres.port
    dbname   = var.db_name
  })
}

# LSQ API key. Created empty; the real key is populated out-of-band (never in
# source control). The lsq_push Lambda reads it via LSQ_SECRET_ARN.
resource "aws_secretsmanager_secret" "lsq" {
  name        = "${local.name_prefix}/lsq-api"
  description = "LSQ bulk API credentials."
  tags        = local.common_tags
}

resource "aws_secretsmanager_secret_version" "lsq" {
  secret_id = aws_secretsmanager_secret.lsq.id
  secret_string = jsonencode({
    api_key  = "REPLACE_ME_OUT_OF_BAND"
    base_url = var.lsq_api_base_url
  })

  lifecycle {
    # Allow the value to be updated outside Terraform without drift noise.
    ignore_changes = [secret_string]
  }
}
