# Database credentials. The password is generated by Terraform and stored only in
# Secrets Manager; the Lambdas read it at runtime via DB_SECRET_ARN.
resource "aws_secretsmanager_secret" "db" {
  name        = "${local.name_prefix}/db-credentials"
  description = "Postgres credentials for the lead assignment engine."

  # Delete immediately instead of the 30-day default recovery window. A deleted
  # secret keeps its name reserved for the whole window, so a destroy followed by
  # a re-apply fails with "already scheduled for deletion" - the exact loop you
  # hit while iterating in a lab account. Nothing here is worth recovering: the
  # password is regenerated on every apply and the account is wiped after the
  # event.
  recovery_window_in_days = 0

  tags = local.common_tags
}

resource "aws_secretsmanager_secret_version" "db" {
  secret_id = aws_secretsmanager_secret.db.id
  secret_string = jsonencode({
    username = var.db_username
    password = random_password.db.result
    host     = aws_db_instance.postgres.address
    port     = aws_db_instance.postgres.port
    dbname   = var.db_name
  })
}

# LSQ API credentials. Created with placeholders; the real values are populated
# out-of-band (never in source control). The lsq_push Lambda reads them via
# LSQ_SECRET_ARN. The bulk update endpoint needs BOTH accessKey and secretKey.
resource "aws_secretsmanager_secret" "lsq" {
  name        = "${local.name_prefix}/lsq-api"
  description = "LSQ bulk API credentials."

  # Same reasoning as the db secret: no recovery window, so destroy/re-apply
  # cycles do not collide on the reserved name.
  recovery_window_in_days = 0

  tags = local.common_tags
}

resource "aws_secretsmanager_secret_version" "lsq" {
  secret_id = aws_secretsmanager_secret.lsq.id
  secret_string = jsonencode({
    api_key    = "REPLACE_ME_OUT_OF_BAND"
    secret_key = "REPLACE_ME_OUT_OF_BAND"
    base_url   = var.lsq_api_base_url
  })

  lifecycle {
    # Allow the value to be updated outside Terraform without drift noise.
    ignore_changes = [secret_string]
  }
}
